# Generated by Django 3.1.7 on 2021-07-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='books_fee',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='books_paid',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Not Paid', 'Not Paid')], max_length=10, null=True),
        ),
    ]
