# Generated by Django 3.1.7 on 2021-07-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_auto_20210707_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Id_card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=1000)),
                ('reg_no', models.PositiveIntegerField()),
                ('fathername', models.CharField(max_length=1000)),
                ('dob', models.DateField()),
                ('classname', models.CharField(choices=[('Nursery', 'Nursery'), ('L.K.G', 'L.K.G'), ('U.K.G', 'U.K.G'), ('1ˢᵗ', '1ˢᵗ'), ('2ⁿᵈ', '2ⁿᵈ'), ('3ʳᵈ', '3ʳᵈ'), ('4ᵗʰ', '4ᵗʰ'), ('5ᵗʰ', '5ᵗʰ'), ('6ᵗʰ', '6ᵗʰ'), ('7ᵗʰ', '7ᵗʰ'), ('8ᵗʰ', '8ᵗʰ'), ('9ᵗʰ', '9ᵗʰ'), ('10ᵗʰ', '10ᵗʰ')], max_length=30)),
                ('bloodgroup', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=30)),
                ('resident_add', models.CharField(max_length=2000)),
                ('permanent_add', models.CharField(max_length=2000)),
            ],
        ),
    ]
