# Generated by Django 3.1.7 on 2021-07-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_id_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='id_card',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
